---
- name: Clone {{ item.key }}
  git:
    clone: true
    dest: "{{ pwd }}/{{ item.key }}"
    repo: "{{ item.value.repo }}"
    version: "{{ item.value.checkout }}"
    depth: 1

- name: Patch {{ item.key }}
  when: item.value.patch is defined
  shell:
    chdir: "{{ pwd }}/{{ item.key }}"
    cmd: git apply {{ patch_dir }}/{{ item.key }}.patch
  register: git_patch

- debug:
    var: git_patch