---
- name: Clone {{ item.key }}
  git:
    clone: true
    dest: "{{ pwd }}/{{ item.key }}"
    repo: "{{ item.value.repo }}"
    version: "{{ item.value.checkout }}"
    depth: 1

- name: Patch {{ item.key }}
  when: item.value.patch is defined
  vars:
    src: "{{ patch_template_dir }}/{{ item.key }}.patch"
    dest: "{{ patch_dir }}/{{ item.key }}.patch"
  include_tasks: patch.yml